package com.bookmyspace.bookmyspace.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flagEmoji: String,
    val locale: Locale
) {
    ENGLISH("en", "English", "English", "🇬🇧", Locale("en", "US")),
    HINDI("hi", "Hindi", "हिंदी", "🇮🇳", Locale("hi", "IN")),
    TELUGU("te", "Telugu", "తెలుగు", "🇮🇳", Locale("te", "IN")),
    TAMIL("ta", "Tamil", "தமிழ்", "🇮🇳", Locale("ta", "IN")),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ", "🇮🇳", Locale("kn", "IN")),
    MARATHI("mr", "Marathi", "मराठी", "🇮🇳", Locale("mr", "IN")),
    BENGALI("bn", "Bengali", "বাংলা", "🇮🇳", Locale("bn", "IN")),
    GUJARATI("gu", "Gujarati", "ગુજરાતી", "🇮🇳", Locale("gu", "IN")),
    MALAYALAM("ml", "Malayalam", "മലയാളം", "🇮🇳", Locale("ml", "IN")),
    SPANISH("es", "Spanish", "Español", "🇪🇸", Locale("es", "ES"))
}

object LocalizedStrings {
    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "BookMySpace",
            "search_placeholder" to "Search venue, PG, hotel...",
            "easy_voice_title" to "Bol-ke-Book (Voice Search)",
            "easy_voice_sub" to "1-Tap Booking with Pictures & Voice",
            "quick_book_title" to "1-Tap Quick Book Mode",
            "quick_book_sub" to "Saved preferences for instant booking",
            "featured_venues" to "Featured Venues & Function Halls",
            "pg_hostels" to "Budget PG & Hostels",
            "hotels" to "Hotels & Day Stays",
            "call_manager" to "Call Manager",
            "whatsapp_manager" to "WhatsApp",
            "quick_book_now" to "1-TAP QUICK BOOK",
            "listen" to "Listen",
            "help_chat" to "Help Chat",
            "select_language" to "Select Language",
            "language_changed" to "Language changed to English",
            "home" to "Home",
            "search" to "Search",
            "map" to "Map",
            "my_bookings" to "My Bookings",
            "saved" to "Saved",
            "profile" to "Profile",
            "book_now" to "Book Now",
            "view_details" to "View Details",
            "filter" to "Filter",
            "sort" to "Sort",
            "cancel" to "Cancel",
            "confirm" to "Confirm",
            "pay_now" to "Pay Now",
            "check_in" to "Check-In",
            "checked_in" to "Checked In",
            "download_pass" to "Download Entry Pass",
            "owner_portal" to "Owner Portal",
            "total_earnings" to "Total Earnings",
            "weekly_calendar" to "Weekly Grid",
            "amenities" to "Amenities",
            "location" to "Location",
            "rating" to "Rating",
            "reviews" to "Reviews",
            "capacity" to "Capacity",
            "price" to "Price",
            "share" to "Share",
            "apply" to "Apply",
            "close" to "Close",
            "save" to "Save",
            "wallet_balance" to "Wallet Balance"
        ),
        AppLanguage.HINDI to mapOf(
            "app_name" to "बुक माय स्पेस",
            "search_placeholder" to "स्थान, पीजी, होटल खोजें...",
            "easy_voice_title" to "बोल-के-बुक (वॉइस सर्च)",
            "easy_voice_sub" to "चित्रों और आवाज़ से 1-टैप बुकिंग",
            "quick_book_title" to "1-टैप त्वरित बुकिंग मोड",
            "quick_book_sub" to "तुरंत बुकिंग के लिए सहेजी गई प्राथमिकताएं",
            "featured_venues" to "प्रमुख मैरिज हॉल और स्थान",
            "pg_hostels" to "बजट पीजी और हॉस्टल",
            "hotels" to "होटल और कमरे",
            "call_manager" to "मैनेजर को कॉल करें",
            "whatsapp_manager" to "व्हाट्सएप",
            "quick_book_now" to "1-टैप त्वरित बुक",
            "listen" to "सुने",
            "help_chat" to "सहायता चैट",
            "select_language" to "भाषा चुनें",
            "language_changed" to "भाषा हिंदी में बदली गई",
            "home" to "होम",
            "search" to "खोजें",
            "my_bookings" to "मेरी बुकिंग",
            "saved" to "सहेजे गए",
            "profile" to "प्रोफ़ाइल",
            "book_now" to "अभी बुक करें",
            "view_details" to "विवरण देखें",
            "filter" to "फ़िल्टर",
            "sort" to "क्रमानुसार",
            "cancel" to "रद्द करें",
            "confirm" to "पुष्टि करें",
            "pay_now" to "अभी भुगतान करें",
            "check_in" to "चेक-इन",
            "checked_in" to "चेक-इन पूर्ण",
            "download_pass" to "पास डाउनलोड करें",
            "owner_portal" to "ओनर पोर्टल",
            "total_earnings" to "कुल कमाई",
            "weekly_calendar" to "साप्ताहिक ग्रिड",
            "amenities" to "सुविधाएं",
            "location" to "स्थान",
            "rating" to "रेटिंग",
            "reviews" to "समीक्षाएं",
            "capacity" to "क्षमता",
            "price" to "मूल्य",
            "share" to "शेयर",
            "apply" to "लागू करें",
            "close" to "बंद करें",
            "save" to "सहेजें",
            "wallet_balance" to "वॉलेट बैलेंस"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_name" to "బుక్ మై స్పేస్",
            "search_placeholder" to "ఫంక్షన్ హాల్, పిజి, హోటల్ వెతకండి...",
            "easy_voice_title" to "బోల్-కే-బుక్ (వాయిస్ సెర్చ్)",
            "easy_voice_sub" to "చిత్రాలు మరియు వాయిస్‌తో 1-ట్యాప్ బుకింగ్",
            "quick_book_title" to "1-ట్యాప్ క్విక్ బుకింగ్ మోడ్",
            "quick_book_sub" to "క్షణంలో బుకింగ్ కోసం సేవ్ చేసిన ప్రాధాన్యతలు",
            "featured_venues" to "ప్రసిద్ధ ఫంక్షన్ హాళ్లు & వేదికలు",
            "pg_hostels" to "బడ్జెట్ పిజి & హాస్టళ్ళు",
            "hotels" to "హోటల్స్ & రూమ్‌లు",
            "call_manager" to "మేనేజర్‌కి కాల్ చేయండి",
            "whatsapp_manager" to "వాట్సాప్",
            "quick_book_now" to "1-ట్యాప్ క్విక్ బుక్",
            "listen" to "వినండి",
            "help_chat" to "సహాయం చాట్",
            "select_language" to "భాషను ఎంచుకోండి",
            "language_changed" to "భాష తెలుగులోకి మార్చబడింది",
            "home" to "హోమ్",
            "search" to "శోధించండి",
            "my_bookings" to "నా బుకింగ్‌లు",
            "saved" to "సేవ్ చేసినవి",
            "profile" to "ప్రొఫైల్",
            "book_now" to "ఇప్పుడే బుక్ చేయండి",
            "view_details" to "వివరాలు చూడండి",
            "filter" to "ఫిల్టర్",
            "sort" to "క్రమబద్ధీకరించు",
            "cancel" to "రద్దు చేయండి",
            "confirm" to "సరిచూసుకోండి",
            "pay_now" to "చెల్లించండి",
            "check_in" to "చెకిన్",
            "checked_in" to "చెకిన్ పూర్తయింది",
            "download_pass" to "పాస్ డౌన్‌లోడ్",
            "owner_portal" to "ఓనర్ పోర్టల్",
            "total_earnings" to "మొత్తం సంపాదన",
            "weekly_calendar" to "వారపు గ్రిడ్",
            "amenities" to "వసతులు",
            "location" to "పాంతం",
            "rating" to "రేటింగ్",
            "reviews" to "సమీక్షలు",
            "capacity" to "సామర్థ్యం",
            "price" to "ధర",
            "share" to "షేర్",
            "apply" to "వర్తింపజేయి",
            "close" to "మూసివేయి",
            "save" to "సేవ్",
            "wallet_balance" to "వాలెట్ బ్యాలెన్స్"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_name" to "புக் மை ஸ்பேஸ்",
            "search_placeholder" to "மண்டபம், பிஜி, ஹோட்டல் தேடுக...",
            "easy_voice_title" to "குரல் வழி முன்பதிவு (Voice Search)",
            "easy_voice_sub" to "படங்கள் மற்றும் குரல் மூலம் 1-டேப் புக்கிங்",
            "quick_book_title" to "1-டேப் விரைவு புக்கிங்",
            "quick_book_sub" to "உடனடி புக்கிங்கிற்கு சேமிக்கப்பட்ட விருப்பங்கள்",
            "featured_venues" to "பிரபலமான திருமண மண்டபங்கள்",
            "pg_hostels" to "பிஜி & விடுதிகள்",
            "hotels" to "ஹோட்டல்கள் & அறைகள்",
            "call_manager" to "மேனேஜரை அழைக்கவும்",
            "whatsapp_manager" to "வாட்ஸ்அப்",
            "quick_book_now" to "1-டேப் விரைவு புக்கிங்",
            "listen" to "கேட்க",
            "help_chat" to "உதவி அரட்டை",
            "select_language" to "மொழியைத் தேர்ந்தெடுக்கவும்",
            "language_changed" to "மொழி தமிழுக்கு மாற்றப்பட்டது",
            "home" to "முகப்பு",
            "search" to "தேடல்",
            "my_bookings" to "என் பதிவுகள்",
            "saved" to "சேமித்தவை",
            "profile" to "சுயவிவரம்",
            "book_now" to "இப்போது முன்பதிவு செய்",
            "view_details" to "விவரங்களைப் பார்க்க",
            "filter" to "வடிகட்டி",
            "sort" to "வரிசைப்படுத்து",
            "cancel" to "ரத்துசெய்",
            "confirm" to "உறுதிசெய்",
            "pay_now" to "பணம் செலுத்து",
            "check_in" to "செக்-இன்",
            "checked_in" to "செக்-இன் முடிந்தது",
            "download_pass" to "பாஸ் பதிவிறக்கம்",
            "owner_portal" to "உரிமையாளர் தளம்",
            "total_earnings" to "மொத்த வருமானம்",
            "weekly_calendar" to "வாராந்திர கட்டம்",
            "amenities" to "வசதிகள்",
            "location" to "இடம்",
            "rating" to "மதிப்பீடு",
            "reviews" to "விமர்சனங்கள்",
            "capacity" to "கொள்திறன்",
            "price" to "விலை",
            "share" to "பகிர்",
            "apply" to "பயன்படுத்து",
            "close" to "மூடு",
            "save" to "சேமி",
            "wallet_balance" to "வாலட் இருப்பு"
        ),
        AppLanguage.KANNADA to mapOf(
            "app_name" to "ಬುಕ್ ಮೈ ಸ್ಪೇಸ್",
            "search_placeholder" to "ಫಂಕ್ಷನ್ ಹಾಲ್, ಪಿಜಿ, ಹೋಟೆಲ್ ಹುಡುಕಿ...",
            "easy_voice_title" to "ಧ್ವನಿ ಹುಡುಕಾಟ (Voice Search)",
            "easy_voice_sub" to "ಚಿತ್ರಗಳು ಮತ್ತು ಧ್ವನಿಯೊಂದಿಗೆ 1-ಟ್ಯಾಪ್ ಬುಕಿಂಗ್",
            "quick_book_title" to "1-ಟ್ಯಾಪ್ ಕ್ವಿಕ್ ಬುಕಿಂಗ್",
            "quick_book_sub" to "ತಕ್ಷಣದ ಬುಕಿಂಗ್‌ಗಾಗಿ ಉಳಿಸಿದ ಆದ್ಯತೆಗಳು",
            "featured_venues" to "ಜನಪ್ರಿಯ ಮದುವೆ ಮಂಟಪಗಳು",
            "pg_hostels" to "ಪಿಜಿ ಮತ್ತು ಹಾಸ್ಟೆಲ್‌ಗಳು",
            "hotels" to "ಹೋಟೆಲ್‌ಗಳು ಮತ್ತು ರೂಮ್‌ಗಳು",
            "call_manager" to "ಮ್ಯಾನೇಜರ್‌ಗೆ ಕರೆ ಮಾಡಿ",
            "whatsapp_manager" to "ವಾಟ್ಸಾಪ್",
            "quick_book_now" to "1-ಟ್ಯಾಪ್ ಕ್ವಿಕ್ ಬುಕ್",
            "listen" to "ಕೇಳಿ",
            "help_chat" to "ಸಹಾಯ ಚಾಟ್",
            "select_language" to "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
            "language_changed" to "ಭಾಷೆಯನ್ನು ಕನ್ನಡಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ",
            "home" to "ಹೋಮ್",
            "search" to "ಹುಡುಕಿ",
            "my_bookings" to "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",
            "saved" to "ಉಳಿಸಿದವು",
            "profile" to "ಪ್ರೊಫೈಲ್",
            "book_now" to "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ",
            "view_details" to "ವಿವರ ನೋಡಿ",
            "filter" to "ಫಿಲ್ಟರ್",
            "sort" to "ವಿಂಗಡಿಸು",
            "cancel" to "ರದ್ದುಮಾಡಿ",
            "confirm" to "ಖಚಿತಪಡಿಸಿ",
            "pay_now" to "ಈಗ ಪಾವತಿಸಿ",
            "check_in" to "ಚೆಕ್-ಇನ್",
            "checked_in" to "ಚೆಕ್-ಇನ್ ಮುಗಿದಿದೆ",
            "download_pass" to "ಪಾಸ್ ಡೌನ್‌ಲೋಡ್",
            "owner_portal" to "ಮಾಲೀಕರ ಪೋರ್ಟಲ್",
            "total_earnings" to "ಒಟ್ಟು ಗಳಿಕೆ",
            "weekly_calendar" to "ವಾರದ ಗ್ರಿಡ್",
            "amenities" to "ಸೌಲಭ್ಯಗಳು",
            "location" to "ಸ್ಥಳ",
            "rating" to "ರೇಟಿಂಗ್",
            "reviews" to "ವಿಮರ್ಶೆಗಳು",
            "capacity" to "ಸಾಮರ್ಥ್ಯ",
            "price" to "ಬೆಲೆ",
            "share" to "ಹಂಚಿಕೊಳ್ಳಿ",
            "apply" to "ಅನ್ವಯಿಸಿ",
            "close" to "ಮುಚ್ಚಿ",
            "save" to "ಉಳಿಸಿ",
            "wallet_balance" to "ವ್ಯಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_name" to "बुक माय स्पेस",
            "search_placeholder" to "हॉल, पीजी, हॉटेल शोधा...",
            "easy_voice_title" to "बोलून बुक करा (Voice Search)",
            "easy_voice_sub" to "चित्र आणि आवाजाने 1-टॅप बुकिंग",
            "quick_book_title" to "1-टॅप क्विक बुकिंग",
            "quick_book_sub" to "झटपट बुकिंगसाठी सेव्ह केलेल्या पसंती",
            "featured_venues" to "प्रमुख मॅरेज हॉल आणि जागा",
            "pg_hostels" to "बजेट पीजी आणि हॉस्टेल्स",
            "hotels" to "हॉटेल्स आणि रूम्स",
            "call_manager" to "मॅनेजरला कॉल करा",
            "whatsapp_manager" to "व्हॉट्सॲप",
            "quick_book_now" to "1-टॅप त्वरित बुक",
            "listen" to "ऐका",
            "help_chat" to "मदत चॅट",
            "select_language" to "भाषा निवडा",
            "language_changed" to "भाषा मराठीमध्ये बदलली",
            "home" to "होम",
            "search" to "शोधा",
            "my_bookings" to "माझ्या बुकिंग्स",
            "saved" to "सेव्ह केलेले",
            "profile" to "प्रोफाइल",
            "book_now" to "आत्ताच बुक करा",
            "view_details" to "तपशील पहा",
            "filter" to "फिल्टर",
            "sort" to "क्रमवारी",
            "cancel" to "रद्द करा",
            "confirm" to "नक्की करा",
            "pay_now" to "आत्ताच पैसे द्या",
            "check_in" to "चेक-इन",
            "checked_in" to "चेक-इन पूर्ण",
            "download_pass" to "पास डाउनलोड",
            "owner_portal" to "मालिक पोर्टल",
            "total_earnings" to "एकूण कमाई",
            "weekly_calendar" to "साप्ताहिक ग्रिड",
            "amenities" to "सुविधा",
            "location" to "ठिकाण",
            "rating" to "रेटिंग",
            "reviews" to "समीक्षा",
            "capacity" to "क्षमता",
            "price" to "किंमत",
            "share" to "शेअर",
            "apply" to "लागू करा",
            "close" to "बंद करा",
            "save" to "सेव्ह करा",
            "wallet_balance" to "वॉलेट शिल्लक"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_name" to "বুক মাই স্পেস",
            "search_placeholder" to "ভেন্যু, পিজি, হোটেল খুঁজুন...",
            "easy_voice_title" to "ভয়েস সার্চ বুকিং",
            "easy_voice_sub" to "ছবি ও ভয়েসে ১-ট্যাপ বুকিং",
            "quick_book_title" to "১-ট্যাপ কুইক বুকিং",
            "quick_book_sub" to "তাত্ক্ষণিক বুকিংয়ের জন্য সেভ করা পছন্দ",
            "featured_venues" to "জনপ্রিয় কনভেনশন ও ম্যারেজ হল",
            "pg_hostels" to "বাজেট পিজি ও হোস্টেল",
            "hotels" to "হোটেল ও রুম",
            "call_manager" to "ম্যানেজারকে কল করুন",
            "whatsapp_manager" to "হোয়াটসঅ্যাপ",
            "quick_book_now" to "১-ট্যাপ কুইক বুক",
            "listen" to "শুনুন",
            "help_chat" to "সাহায্য চ্যাট",
            "select_language" to "ভাষা নির্বাচন করুন",
            "language_changed" to "ভাষা বাংলায় পরিবর্তন করা হয়েছে",
            "home" to "হোম",
            "search" to "খুঁজুন",
            "my_bookings" to "আমার বুকিং",
            "saved" to "সংরক্ষিত",
            "profile" to "প্রোফাইল",
            "book_now" to "এখনই বুক করুন",
            "view_details" to "বিস্তারিত দেখুন",
            "filter" to "ফিল্টার",
            "sort" to "ক্রমানুসারে",
            "cancel" to "বাতিল করুন",
            "confirm" to "নিশ্চিত করুন",
            "pay_now" to "পেমেন্ট করুন",
            "check_in" to "চেক-ইন",
            "checked_in" to "চেক-ইন সম্পন্ন",
            "download_pass" to "পাস ডাউনলোড",
            "owner_portal" to "ওনার পোর্টাল",
            "total_earnings" to "মোট উপার্জন",
            "weekly_calendar" to "সাপ্তাহিক গ্রিড",
            "amenities" to "সুযোগ-সুবিধা",
            "location" to "অবস্থান",
            "rating" to "রেটিং",
            "reviews" to "রিভিউ",
            "capacity" to "ক্ষমতা",
            "price" to "মূল্য",
            "share" to "শেয়ার",
            "apply" to "প্রয়োগ করুন",
            "close" to "বন্ধ করুন",
            "save" to "সংরক্ষণ করুন",
            "wallet_balance" to "ওয়ালেট ব্যালেন্স"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_name" to "બુક માય સ્પેસ",
            "search_placeholder" to "હોલ, પીજી, હોટેલ શોધો...",
            "easy_voice_title" to "વોઈસ સર્ચ બુકિંગ",
            "easy_voice_sub" to "ચિત્રો અને અવાજ સાથે 1-ટેપ બુકિંગ",
            "quick_book_title" to "1-ટેપ ક્વિક બુકિંગ",
            "quick_book_sub" to "ઝડપી બુકિંગ માટે સેવ કરેલી પસંદગીઓ",
            "featured_venues" to "પ્રસિદ્ધ મેરેજ હોલ અને સ્થળો",
            "pg_hostels" to "બજેટ પીજી અને હોસ્ટેલ",
            "hotels" to "હોટેલ્સ અને રૂમ",
            "call_manager" to "મેનેજરને કોલ કરો",
            "whatsapp_manager" to "વોટ્સએપ",
            "quick_book_now" to "1-ટેપ ક્વિક બુક",
            "listen" to "સાંભળો",
            "help_chat" to "મદદ ચેટ",
            "select_language" to "ભાષા પસંદ કરો",
            "language_changed" to "ભાષા ગુજરાતીમાં બદલાઈ ગઈ",
            "home" to "હોમ",
            "search" to "શોધો",
            "my_bookings" to "મારી બુકિંગ",
            "saved" to "સેવ કરેલ",
            "profile" to "પ્રોફાઈલ",
            "book_now" to "હમણાં બુક કરો",
            "view_details" to "વિગતો જુઓ",
            "filter" to "ફિલ્ટર",
            "sort" to "ક્રમમાં રાખો",
            "cancel" to "રદ કરો",
            "confirm" to "કન્ફર્મ કરો",
            "pay_now" to "હમણાં ચૂકવો",
            "check_in" to "ચેક-ઇન",
            "checked_in" to "ચેક-ઇન પૂર્ણ",
            "download_pass" to "પાસ ડાઉનલોડ",
            "owner_portal" to "ઓનર પોર્ટલ",
            "total_earnings" to "કુલ કમાણી",
            "weekly_calendar" to "અઠવાડિક ગ્રિડ",
            "amenities" to "સુવિધાઓ",
            "location" to "સ્થળ",
            "rating" to "રેટિંગ",
            "reviews" to "રિવ્યુ",
            "capacity" to "ક્ષમતા",
            "price" to "કિંમત",
            "share" to "શેર",
            "apply" to "લાગુ કરો",
            "close" to "બંધ કરો",
            "save" to "સેવ કરો",
            "wallet_balance" to "વોલેટ બેલેન્સ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_name" to "ബുക്ക് മൈ സ്‌പേസ്",
            "search_placeholder" to "ഹാൾ, പിജി, ഹോട്ടൽ തിരയുക...",
            "easy_voice_title" to "വോയ്‌സ് തിരച്ചിൽ (Voice Search)",
            "easy_voice_sub" to "ചിത്രങ്ങളും ശബ്ദവും ഉപയോഗിച്ച് 1-ടാപ്പ് ബുക്കിംഗ്",
            "quick_book_title" to "1-ടാപ്പ് ക്വിക്ക് ബുക്കിംഗ്",
            "quick_book_sub" to "തൽക്ഷണ ബുക്കിംഗിനായി സേവ് ചെയ്‌ത മുൻഗണനകൾ",
            "featured_venues" to "പ്രശസ്തമായ മാര്യേജ് ഹാളുകൾ",
            "pg_hostels" to "ബജറ്റ് പിജി & ഹോസ്റ്റലുകൾ",
            "hotels" to "ഹോട്ടലുകൾ & റൂമുകൾ",
            "call_manager" to "മാനേജരെ വിളിക്കുക",
            "whatsapp_manager" to "വാട്ട്‌സ്ആപ്പ്",
            "quick_book_now" to "1-ടാപ്പ് ക്വിക്ക് ബുക്ക്",
            "listen" to "കേൾക്കുക",
            "help_chat" to "സഹായ ചാറ്റ്",
            "select_language" to "ഭാഷ തിരഞ്ഞെടുക്കുക",
            "language_changed" to "ഭാഷ മലയാളത്തിലേക്ക് മാറ്റി",
            "home" to "ഹോം",
            "search" to "തിരയുക",
            "my_bookings" to "എന്റെ ബുക്കിംഗുകൾ",
            "saved" to "സേവ് ചെയ്‌തവ",
            "profile" to "പ്രൊഫൈൽ",
            "book_now" to "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
            "view_details" to "വിശദാംശങ്ങൾ കാണുക",
            "filter" to "ഫിൽട്ടർ",
            "sort" to "ക്രമീകരിക്കുക",
            "cancel" to "റദ്ദാക്കുക",
            "confirm" to "ഉറപ്പാക്കുക",
            "pay_now" to "ഇപ്പോൾ പണമടയ്ക്കുക",
            "check_in" to "ചെക്ക്-ഇൻ",
            "checked_in" to "ചെക്ക്-ഇൻ പൂർത്തിയായി",
            "download_pass" to "പാസ് ഡൗൺലോഡ്",
            "owner_portal" to "ഓണർ പോർട്ടൽ",
            "total_earnings" to "ആകെ വരുമാനം",
            "weekly_calendar" to "പ്രതിവാര ഗ്രിഡ്",
            "amenities" to "സൗകര്യങ്ങൾ",
            "location" to "സ്ഥലം",
            "rating" to "റേറ്റിംഗ്",
            "reviews" to "അഭിപ്രായങ്ങൾ",
            "capacity" to "ശേഷി",
            "price" to "വില",
            "share" to "പങ്കുവെക്കുക",
            "apply" to "ബാധകമാക്കുക",
            "close" to "അടയ്ക്കുക",
            "save" to "സേവ് ചെയ്യുക",
            "wallet_balance" to "വാലറ്റ് ബാലൻസ്"
        ),
        AppLanguage.SPANISH to mapOf(
            "app_name" to "BookMySpace",
            "search_placeholder" to "Buscar local, PG, hotel...",
            "easy_voice_title" to "Reserva por Voz (Voice Search)",
            "easy_voice_sub" to "Reserva en 1 toque con fotos y voz",
            "quick_book_title" to "Modo Reserva Rápida en 1 Toque",
            "quick_book_sub" to "Preferencias guardadas para reserva instantánea",
            "featured_venues" to "Locales y Salones Destacados",
            "pg_hostels" to "PG y Hostales Económicos",
            "hotels" to "Hoteles y Estancias por Día",
            "call_manager" to "Llamar Gerente",
            "whatsapp_manager" to "WhatsApp",
            "quick_book_now" to "RESERVA RÁPIDA 1-TOQUE",
            "listen" to "Escuchar",
            "help_chat" to "Chat de Ayuda",
            "select_language" to "Seleccionar Idioma",
            "language_changed" to "Idioma cambiado a Español",
            "home" to "Inicio",
            "search" to "Buscar",
            "my_bookings" to "Mis Reservas",
            "saved" to "Guardados",
            "profile" to "Perfil",
            "book_now" to "Reservar Ahora",
            "view_details" to "Ver Detalles",
            "filter" to "Filtrar",
            "sort" to "Ordenar",
            "cancel" to "Cancelar",
            "confirm" to "Confirmar",
            "pay_now" to "Pagar Ahora",
            "check_in" to "Registrarse",
            "checked_in" to "Registrado",
            "download_pass" to "Descargar Pase de Entrada",
            "owner_portal" to "Portal de Propietario",
            "total_earnings" to "Ganancias Totales",
            "weekly_calendar" to "Cuadrícula Semanal",
            "amenities" to "Comodidades",
            "location" to "Ubicación",
            "rating" to "Calificación",
            "reviews" to "Reseñas",
            "capacity" to "Capacidad",
            "price" to "Precio",
            "share" to "Compartir",
            "apply" to "Aplicar",
            "close" to "Cerrar",
            "save" to "Guardar",
            "wallet_balance" to "Saldo en Monedero"
        )
    )

    private val _currentLanguage = MutableStateFlow(AppLanguage.ENGLISH)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    fun setLanguage(lang: AppLanguage) {
        _currentLanguage.value = lang
    }

    /**
     * Composable string resource accessor. Observing this automatically triggers
     * recomposition when the current app language changes.
     */
    @Composable
    fun get(key: String): String {
        val currentLang by currentLanguage.collectAsState()
        val langMap = translations[currentLang] ?: translations[AppLanguage.ENGLISH]!!
        return langMap[key] ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    /**
     * Non-composable accessor for background tasks or helper classes.
     */
    fun getDirect(key: String, lang: AppLanguage = _currentLanguage.value): String {
        val langMap = translations[lang] ?: translations[AppLanguage.ENGLISH]!!
        return langMap[key] ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }
}

