[CmdletBinding()]
param([string]$ZipPath='C:\Users\windows\Downloads\PINCODES.zip',[switch]$Reset,[int]$PageTimeoutSeconds=60,[int]$MaxPdfs=0,[switch]$ValidateCheckpoint,[switch]$DryRun)
$ErrorActionPreference='Stop';$root=Join-Path ([IO.Path]::GetTempPath()) 'bookmyspace-pincodes-metadata-audit';if($Reset -and(Test-Path $root)){Remove-Item $root -Recurse -Force};New-Item $root -ItemType Directory -Force|Out-Null;$statePath=Join-Path $root 'metadata-state.json';$state=[pscustomobject]@{files=$null};if(Test-Path $statePath){try{$state=Get-Content -Raw -LiteralPath $statePath|ConvertFrom-Json}catch{Write-Output ("STATE_LOAD_FAILED|"+$_.Exception.Message);exit 2}}
function Get-StateCheckpoint($hash){if($null -eq $state.files){return $null};$property=$state.files.PSObject.Properties[$hash];if($null -eq $property){return $null};return $property.Value}
function Get-Hash($entry){$sha=[Security.Cryptography.SHA256]::Create();$s=$entry.Open();try{return ([BitConverter]::ToString($sha.ComputeHash($s))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose();$sha.Dispose()}}
function Test-Checkpoint($r,$h){if(!$r){return [pscustomobject]@{IsValid=$false;Reason='CHECKPOINT_MISSING'}};$artifact=[string]$r.artifact_path;if([string]::IsNullOrWhiteSpace($artifact)-or !(Test-Path -LiteralPath $artifact -PathType Leaf)){return [pscustomobject]@{IsValid=$false;Reason='ARTIFACT_MISSING'}};$ok=($r.source_sha256 -eq $h)-and($r.status -eq 'COMPLETE')-and([string]$r.records -match '^\d+$')-and([string]$r.error -eq '')-and([int]$r.pages_completed -eq [int]$r.pages_total)-and((Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant() -eq [string]$r.artifact_sha256);if($ok){try{$lines=@(Get-Content -LiteralPath $artifact|ForEach-Object{$_|ConvertFrom-Json});$ok=($lines.Count -eq [int]$r.records)}catch{$ok=$false}};[pscustomobject]@{IsValid=$ok;Reason=if($ok){$null}else{'CHECKPOINT_INVALID'}}}
function Save-State{$tmp="$statePath.tmp";$state|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $tmp -Encoding utf8;Move-Item -LiteralPath $tmp -Destination $statePath -Force}
function Process-Pdf($pdf,$hash,$artifact){$py=@'
import json,re,sys,tempfile,os
from pypdf import PdfReader
import pypdfium2 as pdfium
import pytesseract
pytesseract.pytesseract.tesseract_cmd=r'C:\Program Files\Tesseract-OCR\tesseract.exe'
pdf,out=sys.argv[1:3];reader=PdfReader(pdf);total=len(reader.pages);count=0
open(out,'w',encoding='utf-8').close()
for page_no,page in enumerate(reader.pages,1):
 text=page.extract_text() or '';mode='TEXT'
 if len(text.strip())<40:
  mode='OCR';doc=pdfium.PdfDocument(pdf);pg=doc[page_no-1];img=pg.render(scale=2).to_pil();text=pytesseract.image_to_string(img);del img;del pg;del doc
 pins=re.findall(r'(?<!\d)\d{6}(?!\d)',text)
 with open(out,'a',encoding='utf-8') as f:
  for row,pin in enumerate(pins,1): f.write(json.dumps({'pincode':pin,'office_name':None,'delivery_status':None,'office_type':None,'circle':None,'region':None,'division':None,'source_pdf':pdf,'source_page':page_no,'source_row':row})+'\n')
 count+=len(pins);print('PAGE %d/%d'%(page_no,total),flush=True);print('MODE '+mode,flush=True);print('RECORDS %d'%count,flush=True)
print('RESULT|%d|%d'%(total,count),flush=True)
'@; & python -c $py $pdf $artifact;if($LASTEXITCODE -ne 0){throw 'pypdf/OCR parser failed'};$lines=@(Get-Content -LiteralPath $artifact|ForEach-Object{$_|ConvertFrom-Json});if($lines.Count -eq 0){throw 'zero extracted records'};$pages=(@($lines|ForEach-Object source_page|Sort-Object -Unique).Count);$state.files|Add-Member -NotePropertyName $hash -NotePropertyValue ([pscustomobject]@{source_sha256=$hash;status='COMPLETE';records=$lines.Count;artifact_path=$artifact;artifact_sha256=(Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant();pages_total=$pages;pages_completed=$pages;error=$null}) -Force;Save-State}
if(!(Test-Path $ZipPath)){Write-Output 'PINCODES_ZIP_MISSING';exit 2};Add-Type -AssemblyName System.IO.Compression;$a=[IO.Compression.ZipFile]::OpenRead((Resolve-Path $ZipPath));$pdfs=@();try{foreach($e in $a.Entries){if($e.FullName-notmatch'(?i)\.pdf$'){continue};$pdfs+=[pscustomobject]@{source=$e.FullName;hash=(Get-Hash $e)}}}finally{$a.Dispose()};$pdfs=@($pdfs|Sort-Object source|Group-Object hash|ForEach-Object{$_.Group|Select-Object -First 1});$complete=0;$candidates=@();foreach($p in $pdfs){$v=Test-Checkpoint (Get-StateCheckpoint $p.hash) $p.hash;if($v.IsValid){$complete++;if($ValidateCheckpoint){Write-Output "CHECKPOINT_VALID|$($p.source)"}}else{$candidates+=$p;if($ValidateCheckpoint){Write-Output "CHECKPOINT_INVALID|$($p.source)|reason=$($v.Reason)"}}};Write-Output "TOTAL UNIQUE PDFs: $($pdfs.Count)";Write-Output "COMPLETE: $complete";Write-Output "INCOMPLETE: $($candidates.Count)";if($ValidateCheckpoint -or $DryRun){foreach($p in @($candidates|Select-Object -First $(if($MaxPdfs){$MaxPdfs}else{$candidates.Count}))){Write-Output "PROCESS_CANDIDATE|$($p.source)"};exit 0};$selected=@($candidates|Select-Object -First $(if($MaxPdfs){$MaxPdfs}else{$candidates.Count}));foreach($p in $selected){Write-Output "SELECTED_CANDIDATE|$($p.source)";$tmp=Join-Path $root ('input_'+$p.hash+'.pdf');$z=[IO.Compression.ZipFile]::OpenRead((Resolve-Path $ZipPath));try{$en=$z.Entries|Where-Object FullName -eq $p.source;[IO.Compression.ZipFileExtensions]::ExtractToFile($en,$tmp,$true)}finally{$z.Dispose()};Process-Pdf $tmp $p.hash (Join-Path $root (($p.source -replace '[^A-Za-z0-9_.-]','_')+'_'+$p.hash.Substring(0,12)+'.jsonl'))};Write-Output 'Database writes: 0';Write-Output 'Production: UNTOUCHED'
