[CmdletBinding()]
param([int]$MaxWorkers=1,[int]$MaxZipsPerWorker=1,[int]$MaxWorkbooks=1,[int]$MaxRowsPerRun=100,[string]$SourceRoot='data\location\sources',[string]$AuditRoot='',[string]$WorkerId='', [switch]$Worker,[switch]$DryRun,[switch]$IsolatedTest,[switch]$CompleteSkipTest)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$root=Join-Path ([IO.Path]::GetTempPath()) 'bookmyspace-lgd-audit'
if(!(Test-Path -LiteralPath $SourceRoot -PathType Container)){Write-Output 'SOURCE_ROOT_INVALID';exit 2};$SourceRoot=(Resolve-Path -LiteralPath $SourceRoot).Path
if($AuditRoot){if(!(Test-Path -LiteralPath $AuditRoot -PathType Container)){Write-Output 'AUDIT_ROOT_INVALID';exit 2};$root=(Resolve-Path -LiteralPath $AuditRoot).Path}
$lockRoot=Join-Path $root 'zip-locks'
if($MaxWorkers -le 0){Write-Output 'MAX_WORKERS_INVALID';exit 2};if($MaxWorkers -gt 2){Write-Output 'MAX_WORKERS_LIMIT=2';exit 2};if(!$Worker -and !$DryRun -and !$IsolatedTest -and !$CompleteSkipTest){$ps=(Get-Process -Id $PID).Path;if(!$ps){$ps=(Get-Command powershell).Source};$logRoot=Join-Path $root 'logs';New-Item $logRoot -ItemType Directory -Force|Out-Null;$children=@();for($i=1;$i -le $MaxWorkers;$i++){$wid='W'+$i;$children+=Start-Process -FilePath $ps -ArgumentList @('-NoProfile','-File',$PSCommandPath,'-Worker','-WorkerId',$wid,'-SourceRoot',$SourceRoot,'-AuditRoot',$root,'-MaxZipsPerWorker',$MaxZipsPerWorker,'-MaxWorkbooks',$MaxWorkbooks,'-MaxRowsPerRun',$MaxRowsPerRun) -RedirectStandardOutput (Join-Path $logRoot ($wid+'.stdout.log')) -RedirectStandardError (Join-Path $logRoot ($wid+'.stderr.log')) -PassThru};$children|Wait-Process;Write-Output ('TWO_INDEPENDENT_PROCESSES='+[bool]($children.Count -eq $MaxWorkers));Write-Output ('WORKER_PIDS_DISTINCT='+[bool](@($children.Id|Sort -Unique).Count -eq $children.Count));exit 0}
function Get-ZipIdentity($zip){$p=[IO.Path]::GetFullPath($zip).ToLowerInvariant();$sha=(Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash.ToLowerInvariant();[pscustomobject]@{Path=$p;Sha=$sha;Key=("$p|$sha")}}
function Acquire-ZipLock($zip){$z=if($zip.Path){$zip}else{Get-ZipIdentity $zip};New-Item -ItemType Directory -Path $lockRoot -Force|Out-Null;$path=Join-Path $lockRoot ($z.Sha+'.lock');$claim=Join-Path $lockRoot ($z.Sha+'.claim');try{$stream=[IO.File]::Open($claim,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$stream.Dispose();New-Item -ItemType Directory -Path $path -ErrorAction Stop|Out-Null;$meta=[pscustomobject]@{pid=$PID;worker=([guid]::NewGuid().ToString('N'));zip_path=$z.Path;zip_sha256=$z.Sha;created=(Get-Date).ToUniversalTime().ToString('o')};$meta|ConvertTo-Json|Set-Content -LiteralPath (Join-Path $path 'owner.json') -Encoding utf8;Write-Output "ZIP_LOCK_ACQUIRED|$($z.Path)";[pscustomobject]@{Acquired=$true;LockPath=$path;ClaimPath=$claim;ZipSha=$z.Sha;WorkerId=$meta.worker}}catch{if($stream){$stream.Dispose()};Write-Output "ZIP_LOCK_REJECTED|$($z.Path)";[pscustomobject]@{Acquired=$false;LockPath=$path;ClaimPath=$claim;ZipSha=$z.Sha;WorkerId=$null}}}
function Release-ZipLock($lock){if($lock -and $lock.Acquired){if($lock.ClaimPath -and (Test-Path -LiteralPath $lock.ClaimPath)){Remove-Item -LiteralPath $lock.ClaimPath -Force};if(Test-Path -LiteralPath $lock.LockPath){Remove-Item -LiteralPath $lock.LockPath -Recurse -Force};Write-Output "ZIP_LOCK_RELEASED|$($lock.ZipSha)"}}
function Test-ZipLock($zip){$z=if($zip.Path){$zip}else{Get-ZipIdentity $zip};Test-Path -LiteralPath (Join-Path $lockRoot ($z.Sha+'.lock'))}
function Write-WorkerLog($event,$zip=''){ $log=Join-Path $root 'logs';New-Item $log -ItemType Directory -Force|Out-Null;Add-Content -LiteralPath (Join-Path $log (($WorkerId)+'.log')) -Value ((Get-Date).ToUniversalTime().ToString('o')+"|$WorkerId|$PID|$event|$zip") }
function Get-OrchestratorCandidates($excluded){$statePath=Join-Path $root 'lgd-state.json';$state=$null;if(Test-Path -LiteralPath $statePath){$state=Get-Content -Raw -LiteralPath $statePath|ConvertFrom-Json};$base=(Resolve-Path $SourceRoot).Path;@(Get-ChildItem -LiteralPath $base -Filter '*.zip'|Sort-Object FullName|ForEach-Object{$z=Get-ZipIdentity $_.FullName;if($excluded.ContainsKey($z.Path)){return};$p=$null;if($state -and $state.files){$prop=$state.files.PSObject.Properties[$z.Path+'|'+$z.Sha];if($prop){$p=$prop.Value}};if(!$p -or $p.status -ne 'COMPLETE' -or $p.source_sha256 -ne $z.Sha){$z}})}
if($Worker){Write-WorkerLog 'WORKER_STARTED';$skipped=@{};$claimed=0;while($claimed -lt $MaxZipsPerWorker){$candidates=@(Get-OrchestratorCandidates $skipped);$candidate=$candidates|Select-Object -First 1;if(!$candidate){break};$path=$candidate.Path;Write-WorkerLog 'CANDIDATE_FOUND' $path;$lock=Acquire-ZipLock $path;if(!$lock.Acquired){$skipped[$path]=$true;Write-WorkerLog 'LOCK_REJECTED' $path;continue};$claimed++;Write-WorkerLog 'LOCK_ACQUIRED' $path;try{$check=@(& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -SourceRoot $SourceRoot -AuditRoot $AuditRoot -ZipPath $path -DryRun);$checkText=$check -join "`n";if(($checkText -match 'COMPLETE: 1') -and ($checkText -notmatch 'INCOMPLETE: 1')){Write-WorkerLog 'ZIP_ALREADY_COMPLETE' $path;continue};Write-WorkerLog 'RUNNER_STARTED' $path;& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -SourceRoot $SourceRoot -AuditRoot $AuditRoot -ZipPath $path -MaxWorkbooks $MaxWorkbooks -MaxRowsPerRun $MaxRowsPerRun;Write-WorkerLog 'RUNNER_FINISHED' $path}finally{Release-ZipLock $lock;Write-WorkerLog 'LOCK_RELEASED' $path}};Write-WorkerLog 'WORKER_FINISHED';exit 0}
if($CompleteSkipTest){$test=Join-Path ([IO.Path]::GetTempPath()) ('lgd-complete-skip-test-'+[guid]::NewGuid().ToString('N'));$lockRoot=Join-Path $test 'locks';New-Item $test -ItemType Directory|Out-Null;$a=Join-Path $test 'ZIP-A.zip';$b=Join-Path $test 'ZIP-B.zip';[IO.File]::WriteAllText($a,'A');[IO.File]::WriteAllText($b,'B');$za=Get-ZipIdentity $a;$zb=Get-ZipIdentity $b;$complete=@{$za.Sha=$true};$la=Acquire-ZipLock $za;if($la.Acquired -and $complete[$za.Sha]){Write-Output 'ZIP_ALREADY_COMPLETE|ZIP-A';Release-ZipLock $la;'RUNNER_INVOKED=NO'}else{'ZIPPATH_COMPLETE_SKIP=FAIL'};$lb=Acquire-ZipLock $zb;if($lb.Acquired){'NEXT_CANDIDATE_AFTER_COMPLETE=PASS'}else{'NEXT_CANDIDATE_AFTER_COMPLETE=FAIL'};Release-ZipLock $lb;if(!(Test-ZipLock $za)-and !(Test-ZipLock $zb)){'LOCKS_REMAINING=0';'LOCK_RELEASE=PASS'}else{'LOCK_RELEASE=FAIL'};Remove-Item -LiteralPath $test -Recurse -Force;exit 0}
if($IsolatedTest){$test=Join-Path ([IO.Path]::GetTempPath()) ('lgd-lock-test-'+[guid]::NewGuid().ToString('N'));$old=$lockRoot;$lockRoot=Join-Path $test 'locks';New-Item $test -ItemType Directory|Out-Null;$a=Join-Path $test 'A.zip';$b=Join-Path $test 'B.zip';[IO.File]::WriteAllText($a,'A');[IO.File]::WriteAllText($b,'B');$za=Get-ZipIdentity $a;$zb=Get-ZipIdentity $b;$l1=Acquire-ZipLock $za;$l2=Acquire-ZipLock $za;if(!$l2.Acquired){$l2=Acquire-ZipLock $zb};if($l1.Acquired -and $l2.Acquired -and $l1.ZipSha-ne$l2.ZipSha){'CLAIMED_ZIPS_UNIQUE=PASS'}else{'CLAIMED_ZIPS_UNIQUE=FAIL'};Release-ZipLock $l1;Release-ZipLock $l2;if(!(Test-ZipLock $za)){'LOCK_RELEASE=PASS'}else{'LOCK_RELEASE=FAIL'};Remove-Item -LiteralPath $test -Recurse -Force;exit 0}
if($DryRun){Write-Output "SOURCE_ROOT_SELECTED=$SourceRoot";Write-Output "AUDIT_ROOT_SELECTED=$root";$dryExcluded=@{};$dryCandidates=@(Get-OrchestratorCandidates $dryExcluded);foreach($z in @($dryCandidates|Select-Object -First $(if($MaxZipsPerWorker){$MaxZipsPerWorker}else{$dryCandidates.Count}))){Write-Output "PROCESS_CANDIDATE|$($z.relative)"};exit 0}
if($DryRun){& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -DryRun -MaxZips $MaxZipsPerWorker;exit $LASTEXITCODE}
$candidate=& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -SourceRoot $SourceRoot -DryRun -MaxZips 1 | Where-Object {$_ -match '^PROCESS_CANDIDATE\|'} | Select-Object -First 1
if($candidate){try{$candidatePath=Join-Path (Resolve-Path $SourceRoot).Path ($candidate.ToString().Substring(18));if(!(Test-Path -LiteralPath $candidatePath -PathType Leaf)){Write-Output "ZIP_INVALID|$candidatePath";exit 2};$lock=Acquire-ZipLock $candidatePath}catch{Write-Output "ZIP_INVALID|$candidate";exit 2}}else{$lock=$null}
if($lock -and $lock.Acquired){try{$check=& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -SourceRoot $SourceRoot -AuditRoot $AuditRoot -ZipPath $lock.Zip.Path -DryRun;if(($check -match 'COMPLETE: 1') -and ($check -notmatch 'INCOMPLETE: 1')){Write-Output "ZIP_ALREADY_COMPLETE|$($lock.Zip.Path)";exit 0};Write-Output "ZIP_CLAIMED|$($lock.Zip.Path)";& (Join-Path $PSScriptRoot 'rebuild_lgd_aggregation_dev.ps1') -SourceRoot $SourceRoot -AuditRoot $AuditRoot -ZipPath $lock.Zip.Path -MaxWorkbooks $MaxWorkbooks -MaxRowsPerRun $MaxRowsPerRun;exit $LASTEXITCODE}finally{Release-ZipLock $lock}}
Write-Output 'NO_AVAILABLE_ZIP'
exit 2
