create table public.commerce_references(
 id uuid primary key default gen_random_uuid(),module text not null,reference_type text not null default 'booking',resource_id uuid not null,reservation_id uuid not null,
 legacy_booking_id uuid unique references public.bookings(id) on delete cascade,owner_user_id uuid not null references auth.users(id),org_id uuid not null references public.organizations(id),customer_user_id uuid not null references auth.users(id),
 amount numeric(14,2) not null check(amount>=0),currency text not null default 'INR',booking_status text not null,payment_status text not null default 'unpaid',refund_status text not null default 'none',metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(module,reservation_id)
);
create index commerce_customer_idx on public.commerce_references(customer_user_id,created_at desc);create index commerce_owner_idx on public.commerce_references(owner_user_id,created_at desc);
alter table public.commerce_references enable row level security;
create policy commerce_reference_read on public.commerce_references for select to authenticated using(customer_user_id=(select auth.uid())or owner_user_id=(select auth.uid())or public.has_role((select auth.uid()),'administrator'));
grant select on public.commerce_references to authenticated;revoke insert,update,delete on public.commerce_references from anon,authenticated;

insert into public.commerce_references(module,resource_id,reservation_id,legacy_booking_id,owner_user_id,org_id,customer_user_id,amount,currency,booking_status,payment_status,metadata)
select case when mr.venue_id is not null then 'meetings' when sr.venue_id is not null then 'sports' else 'function_hall' end,b.venue_id,b.id,b.id,o.owner_user_id,o.id,b.user_id,b.total_amount,b.currency,b.workflow_status,
 case when exists(select 1 from payments x where x.booking_id=b.id and x.status='captured')then 'captured' when b.total_amount=0 and b.workflow_status='confirmed' then 'free' else 'unpaid' end,
 coalesce(b.metadata,'{}'::jsonb)||jsonb_build_object('booking_ref',b.booking_ref,'book_date',b.book_date,'start_time',b.start_time,'end_time',b.end_time,'resource_name',v.name)
from bookings b join venues v on v.id=b.venue_id join organizations o on o.id=v.org_id left join meeting_room_profiles mr on mr.venue_id=v.id left join sports_venue_profiles sr on sr.venue_id=v.id on conflict(module,reservation_id)do nothing;
insert into public.commerce_references(module,resource_id,reservation_id,owner_user_id,org_id,customer_user_id,amount,currency,booking_status,payment_status,metadata)
select 'stays',b.property_id,b.id,o.owner_user_id,o.id,b.user_id,b.total,b.currency,b.status,b.payment_status,jsonb_build_object('booking_ref',b.booking_ref,'check_in',b.check_in,'check_out',b.check_out,'adults',b.adults,'children',b.children,'resource_name',p.name)
from stay_bookings b join accommodation_properties p on p.id=b.property_id join organizations o on o.id=p.org_id on conflict(module,reservation_id)do nothing;

alter table public.payments add column commerce_reference_id uuid references public.commerce_references(id) on delete restrict;update payments p set commerce_reference_id=c.id from commerce_references c where c.legacy_booking_id=p.booking_id;alter table public.payments alter column booking_id drop not null;alter table public.payments add constraint payments_reference_required check(commerce_reference_id is not null or booking_id is not null);create index payments_commerce_idx on public.payments(commerce_reference_id,created_at desc);
alter table public.refunds add column commerce_reference_id uuid references public.commerce_references(id) on delete restrict;update refunds r set commerce_reference_id=c.id from commerce_references c where c.legacy_booking_id=r.booking_id;alter table public.refunds alter column booking_id drop not null;alter table public.refunds add constraint refunds_reference_required check(commerce_reference_id is not null or booking_id is not null);
alter table public.invoices add column commerce_reference_id uuid references public.commerce_references(id) on delete restrict;update invoices i set commerce_reference_id=c.id from commerce_references c where c.legacy_booking_id=i.booking_id;create index invoices_commerce_idx on public.invoices(commerce_reference_id);

create or replace function public.sync_booking_commerce_reference()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare v_module text;v_owner uuid;v_org uuid;v_name text;begin
 select case when exists(select 1 from meeting_room_profiles where venue_id=new.venue_id)then 'meetings' when exists(select 1 from sports_venue_profiles where venue_id=new.venue_id)then 'sports' else 'function_hall' end,o.owner_user_id,o.id,v.name into v_module,v_owner,v_org,v_name from venues v join organizations o on o.id=v.org_id where v.id=new.venue_id;
 insert into commerce_references(module,resource_id,reservation_id,legacy_booking_id,owner_user_id,org_id,customer_user_id,amount,currency,booking_status,payment_status,metadata)values(v_module,new.venue_id,new.id,new.id,v_owner,v_org,new.user_id,new.total_amount,new.currency,new.workflow_status,case when new.total_amount=0 and new.workflow_status='confirmed'then 'free' else 'unpaid'end,coalesce(new.metadata,'{}'::jsonb)||jsonb_build_object('booking_ref',new.booking_ref,'book_date',new.book_date,'start_time',new.start_time,'end_time',new.end_time,'resource_name',v_name))on conflict(module,reservation_id)do update set amount=excluded.amount,booking_status=excluded.booking_status,metadata=excluded.metadata,updated_at=now();return new;end$$;
create trigger sync_booking_commerce after insert or update of total_amount,workflow_status on public.bookings for each row execute function public.sync_booking_commerce_reference();
revoke all on function public.sync_booking_commerce_reference()from public,anon,authenticated;
create or replace function public.sync_stay_commerce_reference()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare v_owner uuid;v_org uuid;v_name text;begin select o.owner_user_id,o.id,p.name into v_owner,v_org,v_name from accommodation_properties p join organizations o on o.id=p.org_id where p.id=new.property_id;insert into commerce_references(module,resource_id,reservation_id,owner_user_id,org_id,customer_user_id,amount,currency,booking_status,payment_status,metadata)values('stays',new.property_id,new.id,v_owner,v_org,new.user_id,new.total,new.currency,new.status,new.payment_status,jsonb_build_object('booking_ref',new.booking_ref,'check_in',new.check_in,'check_out',new.check_out,'adults',new.adults,'children',new.children,'resource_name',v_name))on conflict(module,reservation_id)do update set amount=excluded.amount,booking_status=excluded.booking_status,payment_status=excluded.payment_status,metadata=excluded.metadata,updated_at=now();return new;end$$;
create trigger sync_stay_commerce after insert or update of total,status,payment_status on public.stay_bookings for each row execute function public.sync_stay_commerce_reference();
revoke all on function public.sync_stay_commerce_reference()from public,anon,authenticated;

create or replace function public.commerce_reference_for_booking(p_booking_id uuid)returns uuid language sql stable security definer set search_path=public,pg_temp as $$select id from commerce_references where legacy_booking_id=p_booking_id and(customer_user_id=auth.uid()or owner_user_id=auth.uid()or public.has_role(auth.uid(),'administrator'))$$;revoke all on function public.commerce_reference_for_booking(uuid)from public,anon;grant execute on function public.commerce_reference_for_booking(uuid)to authenticated;
create or replace function public.commerce_reference_for_reservation(p_module text,p_reservation_id uuid)returns uuid language sql stable security definer set search_path=public,pg_temp as $$select id from commerce_references where module=p_module and reservation_id=p_reservation_id and(customer_user_id=auth.uid()or owner_user_id=auth.uid()or public.has_role(auth.uid(),'administrator'))$$;revoke all on function public.commerce_reference_for_reservation(text,uuid)from public,anon;grant execute on function public.commerce_reference_for_reservation(text,uuid)to authenticated;

create or replace function public.apply_commerce_payment(p_reference_id uuid,p_payment_ref text)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare c commerce_references;begin select * into c from commerce_references where id=p_reference_id for update;if not found then raise exception 'commerce reference not found';end if;update commerce_references set payment_status='captured',booking_status='confirmed',updated_at=now()where id=c.id;if c.module='stays'then update stay_bookings set payment_status='captured',status='confirmed',updated_at=now()where id=c.reservation_id and status='payment_pending';else update bookings set workflow_status='paid'where id=c.legacy_booking_id and workflow_status='payment_pending';perform confirm_booking(c.legacy_booking_id,p_payment_ref);end if;end$$;revoke all on function public.apply_commerce_payment(uuid,text)from public,anon,authenticated;grant execute on function public.apply_commerce_payment(uuid,text)to service_role;

create or replace function public.commerce_status(p_reference_id uuid)returns text language sql stable security definer set search_path=public,pg_temp as $$select booking_status from commerce_references where id=p_reference_id and(customer_user_id=auth.uid()or owner_user_id=auth.uid()or public.has_role(auth.uid(),'administrator'))$$;revoke all on function public.commerce_status(uuid)from public,anon;grant execute on function public.commerce_status(uuid)to authenticated;
create or replace function public.commerce_status_for_booking(p_booking_id uuid)returns text language sql stable security definer set search_path=public,pg_temp as $$select booking_status from commerce_references where legacy_booking_id=p_booking_id and(customer_user_id=auth.uid()or owner_user_id=auth.uid()or public.has_role(auth.uid(),'administrator'))$$;revoke all on function public.commerce_status_for_booking(uuid)from public,anon;grant execute on function public.commerce_status_for_booking(uuid)to authenticated;

create or replace function public.apply_commerce_refund(p_reference_id uuid,p_partial boolean)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare c commerce_references;v_status text:=case when p_partial then 'partially_refunded'else 'refunded'end;begin select * into c from commerce_references where id=p_reference_id for update;if not found then raise exception 'commerce reference not found';end if;update commerce_references set payment_status=v_status,refund_status=v_status,booking_status=v_status,updated_at=now()where id=c.id;if c.module='stays'then update stay_bookings set payment_status=v_status,status=v_status,updated_at=now()where id=c.reservation_id;update stay_booking_rooms set active=false where stay_booking_id=c.reservation_id and not p_partial;else update bookings set status=case when p_partial then status else 'refunded'::booking_status end,workflow_status=v_status where id=c.legacy_booking_id;end if;end$$;revoke all on function public.apply_commerce_refund(uuid,boolean)from public,anon,authenticated;grant execute on function public.apply_commerce_refund(uuid,boolean)to service_role;

create or replace function public.issue_commerce_invoice(p_reference_id uuid,p_document_type text,p_invoice jsonb default '{}',p_parent_invoice_id uuid default null)returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare c commerce_references;v_uid uuid:=auth.uid();v_config jsonb;v_seq bigint;v_prefix text;v_number text;v_id uuid;v_paid numeric:=0;v_refund numeric:=0;v_payment_ref text:='';v_method text:='';v_payment_status text:='unpaid';v_status text;begin
 select * into c from commerce_references where id=p_reference_id;if not found then raise exception 'reference not found';end if;if v_uid<>c.owner_user_id and not public.has_role(v_uid,'administrator')and not(p_document_type='receipt'and v_uid=c.customer_user_id and c.booking_status='confirmed')then raise exception 'not permitted' using errcode='42501';end if;if p_document_type not in('receipt','tax_invoice','credit_note')then raise exception 'invalid document type';end if;if p_document_type='credit_note'and not exists(select 1 from invoices where id=p_parent_invoice_id and commerce_reference_id=c.id)then raise exception 'valid parent invoice required';end if;
 select coalesce(amount,0),coalesce(provider_payment_id,''),coalesce(method,''),status::text into v_paid,v_payment_ref,v_method,v_payment_status from payments where commerce_reference_id=c.id and status in('captured','refunded','partially_refunded')order by updated_at desc limit 1;if not found and c.payment_status='free'then v_payment_status:='free';end if;select coalesce(sum(amount),0)into v_refund from refunds where commerce_reference_id=c.id and status='processed';
 insert into invoice_configs(owner_user_id,config)values(c.owner_user_id,'{}')on conflict do nothing;update invoice_configs set next_number=next_number+1 where owner_user_id=c.owner_user_id returning config,next_number-1 into v_config,v_seq;v_prefix:=coalesce(nullif(v_config->>'invoice_prefix',''),case when p_document_type='credit_note'then 'CN'else 'INV'end);v_number:=v_prefix||'-'||lpad(v_seq::text,6,'0');v_status:=case when p_document_type='credit_note'or v_refund>=v_paid and v_refund>0 then 'refunded'when v_refund>0 then 'partially_refunded'when c.booking_status='cancelled'then 'cancelled'else 'issued'end;
 insert into invoices(owner_user_id,customer_user_id,booking_id,commerce_reference_id,parent_invoice_id,document_type,status,sequence_number,invoice_number,currency,subtotal,discount,tax_total,fee_total,total,paid,due,refund,config_snapshot,invoice_snapshot)values(c.owner_user_id,c.customer_user_id,c.legacy_booking_id,c.id,p_parent_invoice_id,p_document_type,v_status,v_seq,v_number,c.currency,coalesce((p_invoice->>'subtotal')::numeric,c.amount),coalesce((p_invoice->>'discount')::numeric,0),coalesce((p_invoice->>'tax_total')::numeric,0),coalesce((p_invoice->>'fee_total')::numeric,0),c.amount,v_paid,greatest(c.amount-v_paid,0),v_refund,v_config,c.metadata||p_invoice||jsonb_build_object('module',c.module,'resource_id',c.resource_id,'reservation_id',c.reservation_id,'invoice_number',v_number,'payment_ref',v_payment_ref,'payment_method',v_method,'payment_status',v_payment_status))returning id into v_id;return v_id;end$$;
revoke all on function public.issue_commerce_invoice(uuid,text,jsonb,uuid)from public,anon;grant execute on function public.issue_commerce_invoice(uuid,text,jsonb,uuid)to authenticated;
create or replace function public.issue_invoice(p_booking_id uuid,p_document_type text,p_invoice jsonb,p_parent_invoice_id uuid default null)returns uuid language sql security definer set search_path=public,pg_temp as $$select issue_commerce_invoice((select id from commerce_references where legacy_booking_id=p_booking_id),p_document_type,p_invoice,p_parent_invoice_id)$$;
revoke all on function public.issue_invoice(uuid,text,jsonb,uuid)from public,anon;grant execute on function public.issue_invoice(uuid,text,jsonb,uuid)to authenticated;

create or replace function public.commerce_receipt(p_reference_id uuid)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select jsonb_build_object('commerce_reference_id',c.id,'booking_id',c.reservation_id,'booking_ref',c.metadata->>'booking_ref','receipt_number',i.invoice_number,'hall_name',c.metadata->>'resource_name','customer_name',coalesce(p.full_name,p.email,'Customer'),'customer_phone',coalesce(p.phone,''),'book_date',coalesce(c.metadata->>'book_date',c.metadata->>'check_in'),'start_time',coalesce(c.metadata->>'start_time',c.metadata->>'check_in'),'end_time',coalesce(c.metadata->>'end_time',c.metadata->>'check_out'),'amount',c.amount,'tax_amount',coalesce(i.tax_total,0),'total_amount',c.amount,'currency',c.currency,'booking_status',c.booking_status,'payment_status',c.payment_status,'payment_ref',coalesce(pay.provider_payment_id,''))from commerce_references c left join profiles p on p.id=c.customer_user_id left join lateral(select * from invoices x where x.commerce_reference_id=c.id order by issued_at desc limit 1)i on true left join lateral(select * from payments x where x.commerce_reference_id=c.id order by created_at desc limit 1)pay on true where c.id=p_reference_id and(c.customer_user_id=auth.uid()or c.owner_user_id=auth.uid()or public.has_role(auth.uid(),'administrator'))$$;revoke all on function public.commerce_receipt(uuid)from public,anon;grant execute on function public.commerce_receipt(uuid)to authenticated;
create or replace function public.customer_booking_receipt(p_booking_id uuid)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select commerce_receipt((select id from commerce_references where legacy_booking_id=p_booking_id))$$;revoke all on function public.customer_booking_receipt(uuid)from public,anon;grant execute on function public.customer_booking_receipt(uuid)to authenticated;
